version: '3'

services:
  db:
    image: "postgres:11"
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
  redis:
    image: redis
    ports:
        - "6379:6379"
  dashboard:
    image: "bertl4398/security_dashboard:latest"
    # build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    image: "bertl4398/security_dashboard:latest"
    # build: .
    command: celery worker --app=astrid -l info
    depends_on:
      - db
      - redis

volumes:
  postgres_data: