# Generated by Django 2.1.7 on 2019-03-20 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_sla', models.CharField(choices=[('B', 'Basic'), ('P', 'Pro'), ('U', 'Unlimited')], default='B', max_length=1)),
                ('policy_name', models.CharField(max_length=200)),
                ('policy_description', models.CharField(max_length=500)),
                ('policy_enabled', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('policy_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_file', models.FileField(upload_to='uploads/')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('allowed_connections', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('policies', models.ManyToManyField(to='dashboard.SecurityPolicy')),
            ],
        ),
    ]
