# Generated by Django 2.1.7 on 2019-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
