# Generated by Django 2.1.7 on 2019-03-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitypolicy',
            name='policy_enabled',
        ),
    ]
