# Generated by Django 2.1.7 on 2019-03-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190318_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
