# Generated by Django 2.1.7 on 2019-03-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190318_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_sla', models.CharField(choices=[('B', 'Basic'), ('P', 'Pro'), ('U', 'Unlimited')], default='B', max_length=1)),
                ('policy_name', models.CharField(max_length=200)),
                ('policy_description', models.CharField(max_length=500)),
                ('policy_enabled', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='allowed_connections',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service'),
        ),
    ]
