# Generated by Django 2.1.7 on 2019-03-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_securitypolicy_policy_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='policies',
            field=models.ManyToManyField(blank=True, to='dashboard.SecurityPolicy'),
        ),
    ]
