# Generated by Django 3.1.2 on 2020-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200622_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
